apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "scoold.ecrHelperServiceAccountName" . }}
  labels:
    {{- include "scoold.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "scoold.ecrHelperServiceAccountName" . }}
  labels:
    {{- include "scoold.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["" ]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "scoold.ecrHelperServiceAccountName" . }}
  labels:
    {{- include "scoold.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "scoold.ecrHelperServiceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "scoold.ecrHelperServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
