apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scoold.ecrAwsSecretName" . }}
  labels:
    {{- include "scoold.labels" . | nindent 4 }}
type: Opaque
stringData:
  aws_access_key_id: {{ required "ecrCredentials.accessKeyId is required" .Values.ecrCredentials.accessKeyId | quote }}
  aws_secret_access_key: {{ required "ecrCredentials.accessSecretKey is required" .Values.ecrCredentials.accessSecretKey | quote }}
