apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scoold.imagePullSecretName" . }}
  labels:
    {{- include "scoold.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "scoold.emptyDockerConfig" . }}
